controller_list:
  - name: fake_manipulator_i5_controller
    type: $(arg fake_execution_type)
    joints:
      - shoulder_joint
      - upperArm_joint
      - foreArm_joint
      - wrist1_joint
      - wrist2_joint
      - wrist3_joint
initial:  # Define initial robot poses.
  - group: manipulator_i5
    pose: zero